[build]
	base = "./"
	publish = "docs/dist/"
	command = "npm ci && npm run compile"

[[redirects]]
  from = "http://releasebump.dev/*"
  to = "https://www.releasebump.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://releasebump.dev/*"
  to = "https://www.releasebump.dev/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
