#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Checks if a file has changed since the previous commit.
# @param {string} $1 The file to check.
function changed {
	git diff --name-only HEAD@{1} HEAD | grep "^$1" > /dev/null 2>&1
}

# Update stale dependencies.
if changed 'package-lock.json'; then
	echo "📦 package-lock.json changed. Running npm install to bring your dependencies up to date."
	npm install
fi
