name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allow manual execution from the Actions tab.
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        uses: actions/setup-node@v3.1.1

      - name: Format and lint source code
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
        run: |
          npm ci
          npm run format
          npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        uses: actions/setup-node@v3.1.1

      - name: Run static analysis
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
        run: |
          npm ci
          npm run typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        uses: actions/setup-node@v3.1.1

      - name: Run tests
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
        run: |
          npm ci
          npm test

  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        uses: actions/setup-node@v3.1.1

      - name: Compile source code
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
        run: |
          npm ci
          npm run compile