name: Compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allow manual execution from the Actions tab.
  workflow_dispatch:

jobs:

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Compile source code
        run: |
          npm ci
          npm run compile